### ISSUE TITLE
print msg : missing parentheses (line 69 adsbibdesk.py)

### ISSUE THREAD

**Issue by suberlak** [jonathansick/ads_bibdesk#64]
A problem lies in incorrect syntax of the error print statement : 

 adsbibdesk --help
Traceback (most recent call last):
  File "/Users/chris/anaconda3/bin/adsbibdesk", line 9, in <module>
    load_entry_point('adsbibdesk==3.2.0', 'console_scripts', 'adsbibdesk')()
  File "/Users/chris/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "/Users/chris/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "/Users/chris/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2229, in load
  File "/Users/chris/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2235, in resolve
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/Users/chris/anaconda3/lib/python3.5/site-packages/adsbibdesk-3.2.0-py3.5.egg/adsbibdesk.py", line 69
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by mmaclow** [comment]
I'm finding the same problem.  Looking at the source, the error message in question is a request to install PyObjC from the given URL.  Doing so using pip ensures that from the command line, I can import AppKit, which is the thing whose failure throws the error.  Nonetheless, I continue to get the error.  So I'm a bit confused about what is going on.
