### ISSUE TITLE
works in sierra?

### ISSUE THREAD

**Issue by fxt44** [jonathansick/ads_bibdesk#65]
does adsbibdesk.py work for you in sierra 10.12.1?
if yes, then its just me. if no, any suggestions?

fxt

**Comment by Morisset** [comment]
I found that adsbibdesk does not work anymore on my 10.10 OSX since a few days.
Looking for ArXiv papers is ok, but no access to ADS.
Ch.

**Comment by fxt44** [comment]
i resolved mine. it appeared to be a combination of either rebooting and/or ads being down for a few days. maybe the latter since you also mention the last few days.

fxt

**Comment by Morisset** [comment]
Seems the bibtex information starts again, but no PDF download.

**Comment by fxt44** [comment]
maybe check or reset your ~/.adsbibdesk .

i prefer to handle the pdf files by-hand myself (i'm adamant about no arxiv stuff in my bibdesk master library) so i run with download_pdf=False . however, as a singular test, i ran with download_pdf=True on a recent mnras article and the appropriate arxiv pdf was inserted into bibdesk.

if you post the doi or ads string of the specific article you are trying and i'll give a whirl to see if it works for me.

i've found it can be useful to insert various logging.info statements into adsbibdesk.py and invoking the local modified copy ./adsbibdesk.py directly to get a better sense of what its doing under various circumstances.

fxt

**Comment by hoiting** [comment]
I installed on sierra 10.12.5 and kept getting the following error message. Any idea where the problem is? Thanks

-----
Starting ADS to BibDesk
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/adsbibdesk", line 11, in <module>
    load_entry_point('adsbibdesk==3.2.0', 'console_scripts', 'adsbibdesk')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/adsbibdesk.py", line 189, in main
    process_articles(args, prefs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/adsbibdesk.py", line 209, in process_articles
    process_token(article_token, prefs, bibdesk)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/adsbibdesk.py", line 239, in process_token
    ads_parser.parse(connector.ads_read)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/adsbibdesk.py", line 1091, in parse
    get_redirect(self.links['preprint'])).netloc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/adsbibdesk.py", line 624, in get_redirect
    return out.geturl()
AttributeError: 'URLError' object has no attribute 'geturl'

**Comment by fxt44** [comment]
my 10.12.5 adsbibdesk is at /usr/local/bin/adsbibdesk and uses /usr/bin/python.

appears you have adsbibdesk within a macports framework. maybe try the above.

good luck!

fxt

**Comment by hoiting** [comment]
Excellent. Work like a charm now. Thanks.

**Comment by fxt44** [comment]
super!

fxt
